### PR TITLE
[minor] upgrade deps and add extra log output

### PR DESCRIPTION
**Pull request by tony-assembly**
@bmon I ran an `npm ci` and also `npm audit fix` which has upgraded a bunch of deps.

Also added a couple of log lines so we can see the output of the version during the run of the script too

not sure if this is a breaking change. is there any way to test it before merging?

### CODE REVIEW

**Review by awilmore — DISMISSED** [review]
Nice, thanks 🙏 

To test, maybe we tag it as v2 and test a few projects that way before moving it back to v1?

**Comment by tony-assembly** [comment]
> Nice, thanks 🙏
> 
> To test, maybe we tag it as v2 and test a few projects that way before moving it back to v1?

thats not a bad idea, should I mark it as a `[major]` then?

**Comment by awilmore** [comment]
> thats not a bad idea, should I mark it as a `[major]` then?

You can actually just reference that action via the branch name.

I tested it with this: https://github.com/mx51/docker-reference-app/pull/153

And got this: https://github.com/mx51/docker-reference-app/actions/runs/10192825512/job/28196341248 :/

**Comment by tony-assembly** [comment]
> > thats not a bad idea, should I mark it as a `[major]` then?
> 
> You can actually just reference that action via the branch name.
> 
> I tested it with this: [mx51/docker-reference-app#153](https://github.com/mx51/docker-reference-app/pull/153)
> 
> And got this: https://github.com/mx51/docker-reference-app/actions/runs/10192825512/job/28196341248 :/

oh! thats actually perfect! 🙏 legend

**Comment by tony-assembly** [comment]
tested and the lib upgrades seemed to have done the trick https://github.com/mx51/mxa-playground/actions/runs/10193155219/job/28197266065

**Review by awilmore — APPROVED** [review]
Nice, thanks for this. It was on our backlog to upgrade this action to node20 🙏

**Comment by tony-assembly** [comment]
> Nice, thanks for this. It was on our backlog to upgrade this action to node20 🙏

doesnt seem like its broken anything so we should be good 🤞 

I also upgraded a bunch of packages and supposedly there arent any vulnerabilities anymore 🤷 

@bmon are you happy to merge this in as a v1 or should be upgrade to v2 just in case? issue being is that we will have to go through all services and bump to v2 😢

**Review by dsouzadarryl — APPROVED** [review]
Nice work. Thanks a lot for this @tony-assembly !

**Comment by bmon** [comment]
Looks like you're all over it. I don't think it should be an issue. The versioning of github actions is a bit weird and as adam said you actually need to move the `v1` ref to your commit after you merge for it to apply. I don't think there should be any issues, but even if it breaks we can still tag manually/fix it - so I say go ahead! Thanks for the update

**Review by bmon — APPROVED** [review]

**Comment by tony-assembly** [comment]
> Looks like you're all over it. I don't think it should be an issue. The versioning of github actions is a bit weird and as adam said you actually need to move the `v1` ref to your commit after you merge for it to apply. I don't think there should be any issues, but even if it breaks we can still tag manually/fix it - so I say go ahead! Thanks for the update

@bmon I am not quite sure what you mean by
> The versioning of github actions is a bit weird and as adam said you actually need to move the v1 ref to your commit after you merge for it to apply.

although I did notice that using v1 in another project doesnt work (it doesnt pick up the latest version). What do we need to do to fix that?

**Comment by bmon** [comment]
see https://github.com/actions/toolkit/blob/main/docs/action-versioning.md#recommendations

**Comment by tony-assembly** [comment]
> see https://github.com/actions/toolkit/blob/main/docs/action-versioning.md#recommendations

Thanks @bmon 🙏 

Adam was kind enough to help me out

**Pull request merged**
